### PR TITLE
Entry text will now go away.

### PR DESCRIPTION
**Pull request by emchang3**
The problem was that the entry text was previously part of the results table. Now, the entry text is part of the base layout, and will not be controlled by filterrific, but rather by front end JavaScript.

I have not attempted to change any functionality pertaining to search results.

#91

### CODE REVIEW

**Comment by andyras** [comment]
The welcome text does disappear when I search, but when I try a test filter (e.g. 4th grade), the welcome text stays. Is that something that can be dealt with outside of filterrific?

**Comment by emchang3** [comment]
That's something I'm working on now. I will add more to the pull request if/when I have a solution, or not.

**Comment by emchang3** [comment]
As the commit suggests, the filters now also remove entry text.

**Comment by andyras** [comment]
I tested again and when I filter the intro text still remains. (filter + keyword search does remove the text).

**Comment by emchang3** [comment]
Odd, it works for me :/
screen shot 2016-05-19 at 3 39 50 pm

**Comment by emchang3** [comment]
Now works in Chrome and Firefox. Does not work in Safari. Have not tested Internet Explorer or Edge.

**Pull request merged**
