### PR TITLE
Codes displaying

### PR DESCRIPTION
**Pull request by emchang3**
screen shot 2016-05-31 at 9 00 22 pm

### CODE REVIEW

**Comment by andyras** [comment]
I merged this, but either I merged improperly or the changes @kyaroch and @emchang3 conflict in a weird way. Now the interface is broken, especially when accordioning.

**Comment by emchang3** [comment]
Odd. It's working for me, at least locally. I'll look at it again when I get a chance.

**Comment by kyaroch** [comment]
I think I might have introduced this problem while fixing merge conflicts. I will take a look.

**Comment by emchang3** [comment]
@kyaroch Yes.

**Comment by emchang3** [comment]
I pulled from the master branch and resolved the UI differences.

**Pull request merged**
